const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');const {timelineAction}=require('./ui_helpers.cjs');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const lang of ['', 'en/']){const page=await b.newPage({viewport:{width:1500,height:1000}});await page.route('**/*',r=>r.request().url()==='http://127.0.0.1/'?r.fulfill({contentType:'text/html',body:fs.readFileSync(lang+'index.html')}):r.abort());await page.goto('http://127.0.0.1/');
 const result=await page.evaluate(async()=>{const p=J.defaultProject();p.lyrics='[00:00]最初のカット\n[00:04]次のカット\n[00:08]最後のカット';p.durationOverride=12;p.overrides={0:{single:true},1:{single:true},2:{single:true}};for(const layer of ['media','foreground']){const c=document.createElement('canvas');c.width=160;c.height=90;J.mediaAssets.set(layer,{element:c,type:'image',file:await new Promise(resolve=>c.toBlob(resolve))});Object.assign(p[layer],{items:[{id:layer,name:layer+'.png',type:'image',width:160,height:90}],manualCuts:true,cutCount:3,timing:{lineTimes:{0:0,1:4,2:8}},cutOverrides:{0:{itemId:layer,technique:null},1:{itemId:layer,technique:null},2:{itemId:layer,technique:null}}});}J.ui.project=p;J.uiApi.syncUI();J.uiApi.replan();
  const snapshot=()=>JSON.stringify(Object.fromEntries(['lyrics','media','foreground'].map(layer=>{
   const cuts=(layer==='lyrics'?J.ui.plan.cuts:J.ui.plan[layer].cuts).filter(c=>layer!=='lyrics'||Number.isInteger(c.part));
   return [layer,cuts.map(c=>{if(layer==='lyrics')c={...c,effectEvents:J.cutEffectsPayload(c,'lyrics',J.ui.plan).details.effectEvents};return Object.fromEntries(['layout','enter','exit','hold','treat','bg','cam','trans','technique','entrance','departure','decor','treatP','camP','bgP','transP','params','seed','effectEvents'].filter(k=>c[k]!==undefined).map(k=>[k,c[k]]));})];
  })));
  const before=snapshot();p.timing.lineTimes={0:0,1:2.8,2:9};p.durationOverride=15;p.fx.density=.95;p.enabled.enter=Object.fromEntries(J.order('enter').map(k=>[k,false]));for(const layer of ['media','foreground'])p[layer].effects={...J.mediaEffectSettings(p,layer),enabled:Object.fromEntries(Object.keys(J.MEDIA_TECH).map(k=>[k,false]))};J.uiApi.replan();const after=snapshot();
  if(before!==after){const a=JSON.parse(before),b=JSON.parse(after);throw Error(JSON.stringify(Object.keys(a).flatMap(l=>a[l].flatMap((c,i)=>[...new Set([...Object.keys(c),...Object.keys(b[l][i]||{})])].filter(k=>JSON.stringify(c[k])!==JSON.stringify(b[l][i]?.[k])).map(k=>({l,i,k,before:c[k],after:b[l][i]?.[k]}))))));}
  const saved=await J.unpackProject(await J.packProject(p,null));J.ui.project=saved.project;J.uiApi.syncUI();J.uiApi.replan();if(snapshot()!==before)throw Error('save/load loses resolved effects');
  const previous=J.ui.project,manual=JSON.parse(JSON.stringify(previous));manual.foreground.cutOverrides[0].entrance='enter_fade';J.ui.project=manual;J.uiApi.replan();if(J.ui.plan.foreground.cuts[0].enter!=='fade')throw Error('explicit entrance edit was ignored');J.ui.project=previous;J.uiApi.replan();
  window.effectSnapshot=snapshot;window.originalSnapshot=before;return true;
 });assert.equal(result,true);
 await timelineAction(page,'[data-layer="lyrics"][data-index="0"]','dice');const changed=await page.evaluate(()=>JSON.parse(effectSnapshot()));const initial=await page.evaluate(()=>JSON.parse(originalSnapshot));assert.notDeepEqual(changed.lyrics[0],initial.lyrics[0]);assert.deepEqual(changed.lyrics.slice(1),initial.lyrics.slice(1));assert.deepEqual(changed.media,initial.media);assert.deepEqual(changed.foreground,initial.foreground);
 await page.locator('#btnShuffle').click();assert.notEqual(await page.evaluate(()=>effectSnapshot()),await page.evaluate(()=>originalSnapshot));await page.close();console.log('PASS automatic effect stability '+(lang||'ja'));
 }}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
