const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const {timelineAction}=require('./ui_helpers.cjs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const locale of ['', 'en/'])for(const width of [1500,390]){
 const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.fulfill({contentType:'text/html',body:fs.readFileSync(locale+'index.html')}));await page.goto('http://test/');
 await page.evaluate(()=>{const p=J.defaultProject();p.lyrics='[00:00]編集テスト';p.durationOverride=8;p.overrides={0:{single:true}};p.lyricCutOptions={'0:0':{details:{mask:{enabled:true,shapes:[{type:'rect',cx:.5,cy:.5,w:.4,h:.4,angle:0,lockAspect:true}]}}}};J.ui.project=p;J.uiApi.syncUI();J.uiApi.replan();J.uiApi.seek(1);});
 const original=await page.evaluate(()=>JSON.stringify(J.ui.project));await timelineAction(page,'[data-layer="lyrics"]','details');
 const dialog=page.locator('#cutDetailsDialog'),undo=dialog.locator('[data-detail-undo]'),redo=dialog.locator('[data-detail-redo]'),reset=dialog.getByRole('button',{name:locale?'Reset':'リセット',exact:true});assert.ok(await undo.isDisabled());assert.ok(await redo.isDisabled());
 assert.equal(await dialog.locator('.cut-details-tabs').evaluate(el=>el.previousElementSibling.className),'cut-details-history');
 await dialog.locator('[data-detail-tab=mask]').click();const input=()=>dialog.locator('[data-mask-field=opacity]');await input().fill('50');await input().fill('20');
 await undo.click();assert.equal(await input().inputValue(),'50');await redo.click();assert.equal(await input().inputValue(),'20');await page.keyboard.press('Control+z');assert.equal(await input().inputValue(),'50');await page.keyboard.press('Control+Shift+z');assert.equal(await input().inputValue(),'20');
 await reset.click();assert.equal(await input().inputValue(),'100');await undo.click();assert.equal(await input().inputValue(),'20');
 await input().fill('60');assert.ok(await redo.isDisabled());await page.keyboard.press('Control+z');assert.equal(await input().inputValue(),'20');await page.keyboard.press('Control+Shift+z');assert.equal(await input().inputValue(),'60');
 const rect=dialog.locator('.cut-mask-handles .area-edit-rect'),before=await dialog.locator('[data-mask-shape=cx]').inputValue();assert.equal(await rect.locator('.area-edit-handle').count(),4);assert.equal(await rect.locator('.area-rotate-handle').count(),4);
 let box=await rect.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+15,box.y+box.height/2+8,{steps:4});await page.mouse.up();
 const moved=await dialog.locator('[data-mask-shape=cx]').inputValue();assert.notEqual(moved,before);await undo.click();assert.equal(await dialog.locator('[data-mask-shape=cx]').inputValue(),before);await redo.click();assert.equal(await dialog.locator('[data-mask-shape=cx]').inputValue(),moved);
 for(const corner of ['nw','ne','sw','se']){const grip=rect.locator('.area-edit-handle.'+corner),g=await grip.boundingBox(),w=await dialog.locator('[data-mask-shape=w]').inputValue();await page.mouse.move(g.x+g.width/2,g.y+g.height/2);await page.mouse.down();await page.mouse.move(g.x+g.width/2+(corner.endsWith('e')?8:-8),g.y+g.height/2+(corner.startsWith('s')?8:-8),{steps:3});await page.mouse.up();assert.ok(+await dialog.locator('[data-mask-shape=w]').inputValue()>+w,corner+' resizes');await undo.click();assert.equal(await dialog.locator('[data-mask-shape=w]').inputValue(),w);}
 const g=await rect.locator('.area-rotate-handle.n').boundingBox();await page.mouse.move(g.x+g.width/2,g.y+g.height/2);await page.mouse.down();await page.mouse.move(g.x+g.width/2+15,g.y+g.height/2+8,{steps:4});await page.mouse.up();assert.ok(Math.abs(+await dialog.locator('[data-mask-shape=angle]').inputValue())>1);await undo.click();assert.equal(+await dialog.locator('[data-mask-shape=angle]').inputValue(),0);
 assert.equal(await page.evaluate(()=>JSON.stringify(J.ui.project)),original,'detail undo is isolated from project');await dialog.getByRole('button',{name:locale?'Cancel':'キャンセル',exact:true}).click();assert.equal(await page.evaluate(()=>JSON.stringify(J.ui.project)),original);assert.deepEqual(errors,[]);console.log(locale||'ja',width,'detail history, reset, keyboard, mask corners and rotation passed');await page.close();
}}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
