const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const lang of ['','en/']){
 const page=await browser.newPage({viewport:{width:1100,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const url='http://localhost/'+lang;
 await page.route('**/*',r=>r.request().url()===url?r.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(__dirname,'..',lang,'index.html'))}):r.abort());await page.goto(url);
 await page.locator('#effectFavorites').click();assert.ok((await page.locator('.favorite-help').innerText()).length>30);await page.locator('.favorite-close').click();
 await page.evaluate(()=>{const p=J.ui.project;p.lyrics='Source|ruby\nTarget|note';p.overrides={0:{single:true},1:{single:true}};p.durationOverride=8;p.timing.lineTimes={0:0,1:4};J.uiApi.syncUI();J.uiApi.replan();});
 async function action(layer,index,action){await page.locator(`.timeline-action[data-layer="${layer}"][data-index="${index}"]`).first().click();await page.locator(`#timelineCutMenu [data-action="${action}"]`).click();}
 page.once('dialog',d=>{assert.match(d.defaultValue(),/1$/);d.accept('My favorite');});await action('lyrics',0,'copy');assert.equal(await page.evaluate(()=>J.ui.project.effectFavorites.length),1);
 await action('lyrics',1,'paste');assert.equal(await page.locator('.favorite-card').count(),1);await page.locator('.favorite-play').click();await page.waitForFunction(()=>document.querySelector('#effectFavoritesDialog').favoritePreview);
 assert.equal(await page.evaluate(()=>document.querySelector('#effectFavoritesDialog').favoritePreview.cut.line),1);assert.deepEqual(await page.evaluate(()=>J.ui.project.lyricCutOptions),{});
 await page.locator('.favorite-name').fill('Renamed');await page.locator('.favorite-name').blur();await page.locator('.favorite-apply').click();assert.equal(await page.locator('#effectFavoritesDialog').count(),0);
 assert.equal(await page.evaluate(()=>J.ui.project.effectFavorites[0].name),'Renamed');
 assert.ok(await page.evaluate(()=>{const saved=J.ui.project.effectFavorites[0].payload;return J.ui.project.lyricCutOptions['1:0'].details.layout===saved.details.layout&&J.ui.plan.cuts.find(c=>c.line===1).text.includes('Target');}));
 // Settings and full-file round trips include favorites, without song contents in settings.
 const round=await page.evaluate(async()=>{const p=J.ui.project,settings=J.settingsProject(p),file=await J.packProject(settings,null),loaded=await J.unpackProject(new File([file],'preset.jizuraichi'));const applied=J.applyProjectSettings(p,loaded.project);const full=await J.unpackProject(new File([await J.packProject(p,null)],'full.jizuraichi'));return {empty:settings.lyrics,name:loaded.project.effectFavorites[0].name,lyrics:applied.lyrics,original:p.lyrics,full:full.project.effectFavorites[0].name,valid:J.normalizeEffectFavorites(loaded.project.effectFavorites).length};});assert.equal(round.empty,'');assert.equal(round.name,'Renamed');assert.equal(round.full,'Renamed');assert.equal(round.lyrics,round.original);assert.equal(round.valid,1);
 // Media has a different favorite group; target material remains its own.
 await page.evaluate(()=>{const p=J.ui.project;for(const layer of ['foreground','media']){const m=p[layer];const c=document.createElement('canvas');c.width=160;c.height=90;c.getContext('2d').fillRect(0,0,160,90);J.mediaAssets.set(layer,{element:c,type:'image'});m.items=[{id:layer,name:layer,type:'image'}];m.manualCuts=true;m.cutCount=1;m.timing.lineTimes={0:0};m.cutOverrides={0:{itemId:layer}};}J.uiApi.replan();});
 page.once('dialog',d=>d.accept('Image favorite'));await action('foreground',0,'copy');await action('media',0,'paste');assert.equal(await page.locator('.favorite-card').count(),1);assert.equal(await page.locator('.favorite-name').inputValue(),'Image favorite');await page.locator('.favorite-play').click();await page.waitForFunction(()=>document.querySelector('#effectFavoritesDialog').favoritePreview);assert.equal(await page.evaluate(()=>document.querySelector('#effectFavoritesDialog').favoritePreview.cut.itemId),'media');await page.locator('.favorite-apply').click();
 await page.locator('#effectFavorites').click();await page.waitForFunction(()=>document.querySelectorAll('.favorite-groups h3').length===2);assert.equal(await page.locator('.favorite-groups h3').count(),2);await page.locator('.favorite-play').last().click();await page.waitForFunction(()=>document.querySelector('#effectFavoritesDialog').favoritePreview);assert.equal(await page.locator('.favorite-error:not(:empty)').count(),0);
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);const box=await page.locator('#effectFavoritesDialog').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=390);await page.screenshot({path:`F:/Codex/preview-test-temp/favorites-${lang?'en':'ja'}.png`,scale:'css'});
 await page.locator('.favorite-delete').first().click();assert.equal(await page.locator('.favorite-card').count(),1);await page.locator('.favorite-delete').click();assert.equal(await page.locator('.favorite-card').count(),0);assert.ok((await page.locator('.favorite-help').innerText()).length>30);await page.keyboard.press('Escape');assert.equal(await page.locator('#effectFavoritesDialog').count(),0);assert.deepEqual(errors,[]);console.log(lang||'ja','favorites passed');await page.close();
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
