const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const locale of ['', 'en/']){
const page=await browser.newPage({viewport:{width:1500,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:8765/'+locale;await page.route('**/*',r=>r.request().url()===url?r.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(__dirname,'..',locale,'index.html'))}):r.abort());await page.goto(url);
await page.evaluate(async()=>{const p=J.defaultProject();p.lyrics='[00:00]最初の歌詞/次の歌詞\n[00:04]最後の歌詞';p.durationOverride=8;p.overrides={0:{area:{x:.2,y:.2,w:.6,h:.6,angle:20},layout:'center'}};for(const layer of ['foreground','media']){const canvas=document.createElement('canvas');canvas.width=400;canvas.height=200;canvas.getContext('2d').fillRect(0,0,400,200);const image=new Image();image.src=canvas.toDataURL();await image.decode();J.mediaAssets.set(layer,{element:image,type:'image'});p[layer]={...p[layer],items:[{id:layer,name:layer+'.png',type:'image',width:400,height:200}],manualCuts:true,cutCount:1,timing:{lineTimes:{0:0}},cutOverrides:{0:{itemId:layer,technique:'none',placement:{cx:.5,cy:.5,w:.6,h:.3,angle:layer==='foreground'?30:0}}}};}J.ui.project=p;J.uiApi.syncUI();J.uiApi.replan();J.uiApi.seek(.3);});
const controls=page.locator('#itemFrames');await page.waitForFunction(()=>document.querySelectorAll('.item-frame-tools').length===3);assert.equal(await page.locator('#showItemFrames').isChecked(),true);assert.equal(await controls.locator('button.item-frame-action').count(),19);
for(const layer of ['media','lyrics','foreground'])assert.deepEqual(await controls.locator(`.item-frame-tools.${layer} .item-frame-action`).evaluateAll(els=>els.map(el=>el.dataset.action)),['lock','dice','disableReroll','copy','paste',...(layer==='lyrics'?['frontmost']:[]),'details']);assert.equal(await page.locator('#areaEditTitle,#areaEditHint').count(),0);
const action=(layer,name)=>controls.locator(`button[data-layer="${layer}"][data-action="${name}"]`).first();
await action('lyrics','lock').click();assert.equal(await action('lyrics','lock').getAttribute('aria-pressed'),'true');await action('lyrics','frontmost').click();assert.equal(await action('lyrics','frontmost').getAttribute('aria-pressed'),'true');
assert.equal(await action('foreground','area').count(),0);await controls.locator('.item-frame-name[data-select-layer="foreground"]').click();await page.waitForFunction(()=>!!J.ui.areaEdit);assert.equal(await controls.isVisible(),true);await page.locator('#areaCancel').click();
await action('media','details').click();await page.locator('#cutDetailsDialog').getByRole('button',{name:locale?'Cancel':'キャンセル',exact:true}).click();
const pixels=await page.locator('#view').evaluate(c=>c.toDataURL());await page.locator('#showItemFrames').uncheck();await page.waitForFunction(()=>document.querySelector('#itemFrames').hidden);assert.equal(await page.locator('#view').evaluate(c=>c.toDataURL()),pixels);await page.locator('#showItemFrames').check();
await page.locator('#btnPlay').click();await page.waitForFunction(()=>[...document.querySelectorAll('.item-frame-action')].every(b=>b.disabled));const before=await page.evaluate(()=>JSON.stringify(J.ui.project));await action('foreground','dice').dispatchEvent('click');assert.equal(await page.evaluate(()=>JSON.stringify(J.ui.project)),before);await page.locator('#btnPlay').click();await page.evaluate(()=>J.uiApi.seek(.3));
await page.waitForFunction(()=>[...document.querySelectorAll('.item-frame-action')].every(b=>!b.disabled));
const cut=await page.evaluate(()=>J.lyricCutsAt(J.ui.plan,J.ui.t)[0]);await controls.locator('.item-frame-name[data-select-layer="lyrics"]').click();await page.locator('#areaDelete').click();assert.equal(await page.evaluate(c=>J.ui.plan.cuts.some(x=>x.line===c.line&&x.part===c.part),cut),false);await page.locator('#btnUndo').click();assert.equal(await page.evaluate(c=>J.ui.plan.cuts.some(x=>x.line===c.line&&x.part===c.part),cut),true);
const mediaBefore=await page.evaluate(()=>J.ui.plan.media.cuts.length);await controls.locator('.item-frame-name[data-select-layer="media"]').click();await page.locator('#areaDelete').click();assert.equal(await page.evaluate(()=>J.ui.plan.media.cuts.length),mediaBefore-1);await page.locator('#btnUndo').click();assert.equal(await page.evaluate(()=>J.ui.plan.media.cuts.length),mediaBefore);
const seed=await page.evaluate(()=>J.ui.plan.foreground.cuts[0].seed);await action('foreground','dice').click();assert.notEqual(await page.evaluate(()=>J.ui.plan.foreground.cuts[0].seed),seed);await page.evaluate(()=>J.uiApi.seek(.3));
await page.screenshot({path:path.join(__dirname,'..','..','item-frames-'+(locale?'en':'ja')+'.png')});
await page.locator('#showItemFrames').uncheck();await page.reload();assert.equal(await page.locator('#showItemFrames').isChecked(),false);assert.deepEqual(errors,[]);console.log(locale||'ja','item frames, controls, playback guard, deletion/undo and persistence passed');await page.close();}
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});

