const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');const {timelineAction}=require('./ui_helpers.cjs');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const lang of ['', 'en/']){
 const p=await b.newPage({viewport:{width:1500,height:1000}});await p.route('**/*',r=>r.request().url()==='http://127.0.0.1/'?r.fulfill({contentType:'text/html',body:fs.readFileSync(lang+'index.html')}):r.abort());await p.goto('http://127.0.0.1/');
 const result=await p.evaluate(()=>{let cases=0;const failures=[];for(const [w,h] of [[320,180],[180,320]])for(const type of J.MASK_SHAPES)for(const angle of [-35,0,47])for(const invert of [false,true]){
  const source=document.createElement('canvas');source.width=w;source.height=h;source.getContext('2d').fillRect(0,0,w,h);const s={type,cx:.43,cy:.55,w:.52,h:.26,angle:31},mask=J.normalizeMask({enabled:true,target:'source',invert,shapes:[s]});
  const expected=document.createElement('canvas');expected.width=w;expected.height=h;const e=expected.getContext('2d');e.fillRect(0,0,w,h);e.globalCompositeOperation=invert?'destination-out':'destination-in';e.beginPath();J.maskShapePath(e,[s],w,h);e.fill();
  const cut={itemId:'fixture',type:'image',start:0,end:4,technique:'none',enter:'cut',exit:'cut',hold:'still',treat:'none',layout:'contain',placement:{cx:.5,cy:.5,w:.7,h:.7,lockAspect:true,angle},mask};J.mediaAssets.set('fixture',{element:source,type:'image'});
  const actual=document.createElement('canvas'),oracle=document.createElement('canvas');actual.width=oracle.width=w;actual.height=oracle.height=h;J.drawMediaCut(actual.getContext('2d'),cut,2);
  const q=oracle.getContext('2d'),r=J.mediaPlacementRect(cut.placement,w,h,w,h);q.translate((r.x+r.w/2)*w,(r.y+r.h/2)*h);q.rotate(angle*Math.PI/180);q.drawImage(expected,-r.w*w/2,-r.h*h/2,r.w*w,r.h*h);
  const a=actual.getContext('2d').getImageData(0,0,w,h).data,o=q.getImageData(0,0,w,h).data;let bad=0;for(let i=3;i<a.length;i+=4)if(Math.abs(a[i]-o[i])>3)bad++;if(bad>w*h*.01)failures.push({w,h,type,angle,invert,bad});
  // A cut mask is fixed to the stage, irrespective of item rotation.
  cut.mask={...mask,target:'cut'};const stage=document.createElement('canvas');stage.width=w;stage.height=h;stage.getContext('2d').fillRect(0,0,w,h);J.maskMediaLayer(stage,cut,2);const st=stage.getContext('2d').getImageData(0,0,w,h).data,ex=e.getImageData(0,0,w,h).data;for(let i=3;i<st.length;i+=4)if(st[i]!==ex[i]){failures.push({type,target:'cut'});break;}cases++;
 }return {cases,failures};});assert.deepEqual(result.failures,[]);
 // The source editing reference must be independent of lyric placement rotation.
 const references=[];for(const angle of [0,38]){await p.evaluate(angle=>{const x=J.defaultProject();x.lyrics='[00:00]MASK';x.durationOverride=4;x.res=640;x.overrides={0:{single:true}};x.fx={...x.fx,texture:0,chroma:0,glitch:0,hud:'off',onTwos:false,koma:0};x.lyricCutOptions={'0:0':{details:{layout:'center',enter:'cut',exit:'cut',hold:'still',cam:'push',camP:{a:0},bg:'none',decor:[],effectStyle:{glow:0,ghost:0},area:{x:.2,y:.2,w:.6,h:.5,angle},mask:{enabled:false,target:'source',shapes:[]}}}};J.ui.project=x;J.uiApi.syncUI();J.uiApi.replan();},angle);
 await timelineAction(p,'[data-layer="lyrics"][data-index="0"]','details');const d=p.locator('#cutDetailsDialog');await d.locator('[data-detail-tab="mask"]').click();references.push(await d.locator('.cut-mask-canvas').evaluate(c=>c.toDataURL()));await d.getByRole('button',{name:lang?'Cancel':'キャンセル',exact:true}).click();}
 assert.equal(references[0],references[1],'source reference removes placement angle');console.log('PASS mask geometry '+(lang||'ja')+' '+result.cases+' rotated material cases and lyric reference');await p.close();
 }}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
