const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const root=fs.mkdtempSync('F:/Codex/preview-test-temp/media-lifetime-');const source=path.join(root,'source.bin');const bytes=process.env.JIZURA_TEST_VIDEO?fs.readFileSync(process.env.JIZURA_TEST_VIDEO):Buffer.alloc(128*1024,7);const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const lang of ['','en/']){
fs.writeFileSync(source,bytes);const page=await browser.newPage();await page.route('**/*',r=>r.request().url()==='http://localhost:8765/'?r.fulfill({contentType:'text/html',body:fs.readFileSync(lang+'index.html')}):r.abort());await page.goto('http://localhost:8765/');await page.evaluate(()=>{J.ui.exporting={};const el=document.createElement('input');el.type='file';el.id='fixtureInput';document.body.append(el)});await page.locator('#fixtureInput').setInputFiles(source);
await page.evaluate(async(video)=>{window.sourceFile=document.getElementById('fixtureInput').files[0];await J.storeMedia('fixture',sourceFile);const p=J.ui.project;p.lyrics='';p.durationOverride=1;p.fps=12;p.videoSize={w:320,h:180};p.videoSizeMode='custom';p.audioAsset={id:'fixture',name:'source.bin'};if(video){const item={id:'fixture',type:'video',name:'source.mp4'};p.media.items=[item];p.media.manualCuts=true;p.media.cutCount=1;p.media.cutOverrides={0:{itemId:'fixture',videoLoop:true}};await J.attachMedia(item,sourceFile);}J.uiApi.replan();},!!process.env.JIZURA_TEST_VIDEO);
// An overwritten source used to invalidate BOTH the video URL and the IndexedDB File.
fs.writeFileSync(source,Buffer.alloc(bytes.length,8));
const result=await page.evaluate(async(video)=>{const stored=await J.loadMedia('fixture'),expected=await J.snapshotMediaFile(sourceFile);const packed=await J.packProject(J.ui.project,sourceFile),unpacked=await J.unpackProject(packed);window.savedBlob=packed;const file=unpacked.files.find(f=>f.kind==='audio').file;const hash=async b=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await b.arrayBuffer()))).join(',');const r={stored:await hash(stored),expected:await hash(expected),packed:await hash(file)};if(video){const el=J.mediaAssets.get('fixture').element;el.loop=true;for(const t of [0,.5,el.duration-.001,el.duration+.1,0])await J.prepareMediaFrame({...J.ui.plan,media:{cuts:[{...J.ui.plan.media.cuts[0],end:el.duration+1}]}},t);const out=await J.exportMP4({project:J.ui.project,plan:J.ui.plan});r.mp4=out.blob.size;}return r;},!!process.env.JIZURA_TEST_VIDEO);
assert.equal(result.stored,result.expected);assert.equal(result.packed,result.expected);if(process.env.JIZURA_TEST_VIDEO)assert.ok(result.mp4>100);
const wait=page.waitForEvent('download');await page.evaluate(()=>J.saveFile('regression.jizuraichi',window.savedBlob));const dl=await wait;assert.equal(await dl.failure(),null);await dl.saveAs(path.join(root,(lang?'en':'ja')+'.jizuraichi'));
console.log(lang||'ja','source overwrite, project download',process.env.JIZURA_TEST_VIDEO?'and real video MP4 export':'','passed');await page.close();}
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
