const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
const wav=Buffer.alloc(44+16000*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const lang of ['','en/'])for(const mode of ['sync','async']){
const page=await browser.newPage();await page.addInitScript(mode=>{const open=IDBFactory.prototype.open;window.failMediaDB=true;IDBFactory.prototype.open=function(name,...args){if(name==='jizura-media-v1'&&window.failMediaDB){const error=new DOMException('Internal error opening backing store for indexedDB.open.','UnknownError');if(mode==='sync')throw error;const request={error};setTimeout(()=>request.onerror?.(),0);return request;}return open.call(this,name,...args);};},mode);
await page.route('**/*',r=>r.request().url()==='http://localhost:8765/'?r.fulfill({contentType:'text/html',body:fs.readFileSync(lang+'index.html')}):r.abort());await page.goto('http://localhost:8765/');
const bytes=process.env.JIZURA_TEST_VIDEO?fs.readFileSync(process.env.JIZURA_TEST_VIDEO):wav;
await page.evaluate(async({base64,video})=>{const file=new File([Uint8Array.from(atob(base64),c=>c.charCodeAt(0))],video?'source.mp4':'source.wav',{type:video?'video/mp4':'audio/wav'});await J.uiApi.loadAudioFile(file,{matchDuration:true,background:video});},{base64:bytes.toString('base64'),video:!!process.env.JIZURA_TEST_VIDEO});
assert.equal(await page.evaluate(()=>!!J.ui.audio&&!!J.ui.project.audioAsset),true);assert.equal(await page.locator('#mediaStorageWarning').isVisible(),true);
// Direct material import must succeed too, independently of audio decoding.
await page.locator('#mediaFiles').setInputFiles({name:'material.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" fill="red"/></svg>')});
await page.waitForFunction(()=>[...J.ui.project.media.items,...J.ui.project.foreground.items].some(i=>i.name==='material.svg'));
const result=await page.evaluate(async()=>{const p=J.ui.project;const blob=await J.packProject(p,J.ui.audioFile),unpacked=await J.unpackProject(blob);await J.saveFile('fallback.jizuraichi',blob);const audio=await J.loadMedia(p.audioAsset.id);return {audio:audio.size,files:unpacked.files.length,temporary:J.hasTemporaryMedia(),video:p.media.items.some(i=>i.type==='video')};});assert.ok(result.audio>0);assert.ok(result.files>=2);assert.ok(result.temporary);if(process.env.JIZURA_TEST_VIDEO)assert.ok(result.video);
// Storage recovering must not lose the session data; retry persistence then reload it.
await page.evaluate(async()=>{window.failMediaDB=false;const p=J.ui.project;for(const id of [p.audioAsset.id,...p.media.items.map(i=>i.id),...p.foreground.items.map(i=>i.id)])await J.storeMedia(id,await J.loadMedia(id));});assert.equal(await page.evaluate(()=>J.hasTemporaryMedia()),false);assert.equal(await page.locator('#mediaStorageWarning').isVisible(),false);
console.log(lang||'ja',mode,'IndexedDB failure: import, project export, recovery passed');await page.close();}
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
