const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const dir=fs.mkdtempSync('F:/Codex/preview-test-temp/restored-media-'),source=path.join(dir,'source.bin');const video=!!process.env.JIZURA_TEST_VIDEO;const bytes=video?fs.readFileSync(process.env.JIZURA_TEST_VIDEO):Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" fill="red"/></svg>');const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const lang of ['','en/']){
fs.writeFileSync(source,bytes);const page=await browser.newPage();await page.route('**/*',r=>r.request().url()==='http://localhost:8765/'?r.fulfill({contentType:'text/html',body:fs.readFileSync(lang+'index.html')}):r.abort());await page.goto('http://localhost:8765/');await page.evaluate(()=>{J.ui.exporting={};const i=document.createElement('input');i.type='file';i.id='fixture';document.body.append(i)});await page.locator('#fixture').setInputFiles(source);
await page.evaluate(async video=>{const original=document.getElementById('fixture').files[0];await new Promise((resolve,reject)=>{const q=indexedDB.open('jizura-media-v1',1);q.onupgradeneeded=()=>q.result.createObjectStore('files');q.onerror=()=>reject(q.error);q.onsuccess=()=>{const db=q.result,tx=db.transaction('files','readwrite');tx.objectStore('files').put(original,'legacy');tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}}});window.restored=await J.loadMedia('legacy');window.assetItem={id:'legacy',name:video?'source.mp4':'source.svg',type:video?'video':'image'};},video);
// The restored object must no longer depend on the original disk-backed File.
fs.writeFileSync(source,Buffer.alloc(bytes.length,8));
const result=await page.evaluate(async()=>{const restoredBytes=new Uint8Array(await restored.arrayBuffer());const first=await J.attachMedia(assetItem,restored),old=J.mediaAssets.get('legacy');await J.attachMedia(assetItem,restored);const replacedReleased=!first.hasAttribute('src')&&(old.type!=='video'||first.readyState===0&&first.paused);const current=J.mediaAssets.get('legacy');J.releaseMediaAsset(current);await J.removeMedia('legacy');return {firstByte:restoredBytes[0],size:restoredBytes.length,replacedReleased,removedReleased:!current.element.hasAttribute('src'),missing:(await J.loadMedia('legacy'))===undefined,stillReadable:(await restored.arrayBuffer()).byteLength};});
assert.equal(result.firstByte,bytes[0]);assert.equal(result.size,bytes.length);assert.ok(result.replacedReleased);assert.ok(result.removedReleased);assert.ok(result.missing);assert.equal(result.stillReadable,bytes.length);console.log(lang||'ja','restored bytes detached; replaced/deleted media released');await page.close();}
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
