const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const lang of ['','en/'])for(const width of [1920,390]){
 const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const url='http://localhost:8765/'+lang;await page.route('**/*',r=>r.request().url()===url?r.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(__dirname,'..',lang,'index.html'))}):r.abort());await page.goto(url);
 await page.evaluate(()=>{J.ui.project.lyrics='First\nSecond\nThird';J.ui.project.durationOverride=15;J.uiApi.syncUI();J.uiApi.replan();});
 await page.locator('#modePro').click();await page.locator('#sourceLyrics').click();await page.locator('#btnTap').click();
 const panel=page.locator('#tapPanel');assert.equal(await panel.isVisible(),true);assert.equal(await page.locator('#settingsDrawer').isVisible(),false);assert.equal(await page.locator('#lyrics').isVisible(),false);
 assert.equal(await panel.evaluate(e=>getComputedStyle(e).position),'absolute');let geometry=await page.evaluate(()=>{const p=document.querySelector('#tapPanel').getBoundingClientRect(),v=document.querySelector('#viewport').getBoundingClientRect();return {gap:p.top-v.bottom,width:p.width,x:p.x};});assert.ok(geometry.gap>=4&&geometry.gap<=8);assert.ok(geometry.width<=width&&geometry.x>=0);
 assert.equal(await page.locator('#tapBtn').isDisabled(),true);await page.locator('#tapBtn').waitFor();await page.waitForFunction(()=>!J.ui.tap?.countingDown);await page.locator('#tapBtn').click();assert.equal(await page.evaluate(()=>J.ui.tap.i),1);assert.ok(await page.evaluate(()=>J.ui.project.timing.lineTimes[0]>=0));
 await page.locator('#tapStop').click();assert.equal(await panel.isVisible(),false);assert.equal(await page.evaluate(()=>J.ui.tap),null);
 // The same shared panel is used for foreground/background insertion, including countdown cancellation.
 for(const [layer,id]of [['foreground','sourceForeground'],['media','sourceMedia']]){await page.evaluate(layer=>{J.ui.project[layer].items=[{id:'fixture',name:'Fixture.png',type:'image'}];J.uiApi.replan();},layer);await page.locator('#'+id).click();await page.locator('#btnTapMedia').click();assert.equal(await panel.isVisible(),true);assert.equal(await page.evaluate(()=>J.ui.tap.layer),layer);assert.equal(await page.locator('#mediaPane').isVisible(),false);await page.locator('#tapStop').click();}
 assert.deepEqual(errors,[]);console.log(lang||'ja',width,'tap overlay passed');await page.close();
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
