const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const lang of ['','en/'])for(const width of [1920,390]){
 const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const url='http://localhost:8765/'+lang;await page.route('**/*',r=>r.request().url()===url?r.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(__dirname,'..',lang,'index.html'))}):r.abort());await page.goto(url);
 await page.evaluate(()=>{J.ui.project.lyrics='First\nSecond\nThird\nFourth';J.ui.project.durationOverride=15;J.uiApi.syncUI();J.uiApi.replan();});
 await page.locator('#modePro').click();await page.locator('#sourceLyrics').click();await page.locator('#btnTap').click();
 const panel=page.locator('#tapPanel');assert.equal(await panel.isVisible(),true);assert.equal(await page.locator('#settingsDrawer').isVisible(),false);assert.equal(await page.locator('#lyrics').isVisible(),false);
 assert.equal(await panel.evaluate(e=>getComputedStyle(e).position),'absolute');let geometry=await page.evaluate(()=>{const p=document.querySelector('#tapPanel').getBoundingClientRect(),v=document.querySelector('#viewport').getBoundingClientRect();return {gap:p.top-v.bottom,width:p.width,x:p.x};});assert.ok(geometry.gap>=4&&geometry.gap<=8);assert.ok(geometry.width<=width&&geometry.x>=0);
 assert.equal(await page.locator('#tapLine').textContent(),'First');assert.equal(await page.locator('#tapLineAhead1').textContent(),'Second');assert.equal(await page.locator('#tapLineAhead2').textContent(),'Third');
 assert.equal(await panel.locator('.tap-current .tap-marker').textContent(),'▶');assert.equal(await panel.locator('.next').textContent(),'▶First');
 assert.equal(await page.locator('#tapHint').textContent(),lang?'Click the button (or press Space) at the moment you want to insert.':'挿入したいタイミングでボタンをクリック（またはスペースキー）');
 const queue=await panel.evaluate(el=>{const rows=[...el.querySelectorAll('.tap-queue-line')];return {opacity:rows.map(r=>+getComputedStyle(r).opacity),y:rows.map(r=>r.getBoundingClientRect().top),font:+getComputedStyle(el.querySelector('#tapHint')).fontSize.replace('px','')}});assert.deepEqual(queue.opacity,[.22,.5,1]);assert.ok(queue.y[0]<queue.y[1]&&queue.y[1]<queue.y[2]);assert.ok(queue.font>=14);
 const tapPositions=()=>page.evaluate(()=>Object.fromEntries(['tapPanel','tapBtn','tapStop'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return [id,{x:r.x,y:r.y,width:r.width,height:r.height}]})));
 const beforeCountdown=await tapPositions();
 assert.equal(await page.locator('#tapBtn').isDisabled(),true);await page.locator('#tapBtn').waitFor();await page.waitForFunction(()=>!J.ui.tap?.countingDown);assert.deepEqual(await tapPositions(),beforeCountdown,'countdown completion preserves panel and control geometry');assert.equal(await page.locator('#tapCountdown').isVisible(),false);await page.locator('#tapBtn').click();assert.equal(await page.evaluate(()=>J.ui.tap.i),1);assert.ok(await page.evaluate(()=>J.ui.project.timing.lineTimes[0]>=0));
 assert.equal(await page.locator('#tapLine').textContent(),'Second');assert.equal(await page.locator('#tapLineAhead1').textContent(),'Third');assert.equal(await page.locator('#tapLineAhead2').textContent(),'Fourth');
 await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>J.ui.tap.i),2);assert.equal(await page.locator('#tapLine').textContent(),'Third');assert.equal(await page.locator('#tapLineAhead1').textContent(),'Fourth');assert.equal(await page.locator('#tapLineAhead2').textContent(),'');
 await page.locator('#tapStop').click();assert.equal(await panel.isVisible(),false);assert.equal(await page.evaluate(()=>J.ui.tap),null);
 // The same shared panel is used for foreground/background insertion, including countdown cancellation.
 for(const [layer,id]of [['foreground','sourceForeground'],['media','sourceMedia']]){await page.evaluate(layer=>{J.ui.project[layer].items=[{id:'fixture',name:'Fixture.png',type:'image'}];J.uiApi.replan();},layer);await page.locator('#'+id).click();await page.locator('#btnTapMedia').click();assert.equal(await panel.isVisible(),true);assert.equal(await page.evaluate(()=>J.ui.tap.layer),layer);assert.equal(await page.locator('#mediaPane').isVisible(),false);assert.equal(await panel.locator('.tap-future-one').isVisible(),false);assert.equal(await panel.locator('.tap-future-two').isVisible(),false);await page.locator('#tapStop').click();}
 assert.deepEqual(errors,[]);console.log(lang||'ja',width,'tap overlay passed');await page.close();
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
