// Editable decoration parameters, including reads in positioning helpers.
// Keep this catalog aligned with each decoration draw implementation.
(() => {
'use strict';
const fields={};
for(const [keys,ids] of [
  ["n", "grid"],
  ["accent corner", "stripes"],
  ["seed n", "blobs bars shapes rings slash sparks glitchRects confetti chochin rainRipples bubbles fireflies musicNotes hrStaticPatch hrDrips"],
  ["right low accent mode from to", "counter"],
  ["accent", "brackets bracketsJP"],
  ["", "dots sonarArcs knWordTicks tyGlyphBody"],
  ["right low big", "arrows"],
  ["seed", "leaders highlightMark glyphLock"],
  ["seed low", "waveform"],
  ["seed right low", "barcode paperClip hrCracks"],
  ["accent v", "crosshair beatRing tyBigPunct"],
  ["accent big r", "cropMarks"],
  ["right low corner v r", "reticle sensu tsukiKumo starburst"],
  ["seed n right low r", "radar"],
  ["right low corner v", "progressRing spinner swatches registration moonPhases stripeCircle halfCircles mediaControls"],
  ["right low", "timecodeBar zigzagRibbon tyColophon"],
  ["right low corner", "rulerEdge"],
  ["right low accent big v", "dimension"],
  ["right low mode v", "indexNum"],
  ["seed right v", "dateStamp ruledLines"],
  ["seed right low accent", "qrBlock seigaiha"],
  ["n right low corner v r", "concentricSquares spiralLine loopArrows"],
  ["right low accent corner big v r", "triangleSpin"],
  ["seed n big", "lineBurst twinkle momiji"],
  ["n right low corner big v r", "plusGrid"],
  ["accent big v", "guides"],
  ["right low accent v", "waveLine checkerStrip"],
  ["seed right low accent v", "halftonePatch"],
  ["n right r", "orbitDots"],
  ["seed n right low corner v", "constellation dataColumns"],
  ["seed n right", "petals snow kasumi cloudPuffs knSpeedTrail"],
  ["seed n right r", "rainStreaks"],
  ["seed right low corner v r", "lightLeak spectrumRing atomOrbit"],
  ["seed n v", "bokeh hanabi memphis hrScratches"],
  ["seed n corner", "speedCorner"],
  ["seed n accent v", "risingParticles"],
  ["seed right low v", "brushStroke"],
  ["seed right big v r", "tapePieces"],
  ["seed right accent v", "scribbleCircle"],
  ["seed accent v", "scribbleUnder"],
  ["right corner v", "crossOut"],
  ["seed n big v", "heartsStars"],
  ["right low v", "watermarkKanji verticalStrip punchHoles staple indexTabs cursorClick tyTypeScale"],
  ["seed low accent v", "romajiLine"],
  ["seed corner v", "seal"],
  ["right low accent corner v r", "kamon"],
  ["seed right low accent corner r", "asanoha"],
  ["n low", "shimenawa"],
  ["right r", "namiGashira"],
  ["seed n right low corner big v r", "hexGrid"],
  ["right low r", "headingTape"],
  ["seed n right big r", "circuit"],
  ["seed right low big", "vines hrWatchEye"],
  ["seed n r", "starField"],
  ["n right low accent v r", "sunRays"],
  ["seed n right v", "smoke"],
  ["seed n right big", "dandelion"],
  ["n right low accent corner v", "polkaPatch"],
  ["corner big", "decoCorners"],
  ["seed n right low accent corner v", "tally"],
  ["v", "windowChrome"],
  ["seed right low corner v", "progressBar notifBell likeCounter volumeBars"],
  ["n right low corner v", "toggleSwitch"],
  ["seed right", "hrSigil hrDustBeam"],
  ["right", "tyRunningHead"],
  ["n low v", "tyTextRule"],
])for(const id of ids.split(' '))fields[id]=keys?keys.split(' '):[];
J.DECOR_DETAIL_FIELDS=fields;
J.decorDetailFields=id=>J.DECOR[id]?.detailFields || fields[id] || [];
J.decorDetailDefaults=seed=>({seed,n:1,right:false,low:false,accent:false,corner:false,big:false,mode:'index',from:0,to:100,v:0,r:.5});
})();
